name: sea_siren_alert
description: Offline safety app for Tamil Nadu fishermen using maps.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Maps
  flutter_map: ^8.2.2
  flutter_map_tile_caching: ^10.1.1
  latlong2: ^0.9.1
  # Location and sensors
  geolocator: ^14.0.2
  # Storage and security
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2
  # Networking and utils
  http: ^1.2.2
  url_launcher: ^6.3.2
  get: ^4.6.6
  intl: ^0.20.2
  # Media and haptics
  audioplayers: ^6.1.0
  vibration: ^3.1.4
  # Telephony/SMS (Android)
  another_telephony: ^0.4.1
  # TTS (optional)
  flutter_tts: ^4.2.3
  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Optional: launcher icons generator
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
    - assets/audio/alert.mp3
    - assets/audio/alert_3km.mp3
    - assets/audio/alert_1km.mp3
    - assets/audio/alert_500m.mp3

