name: sea_siren_alert
description: App to prevent border crossings for Tamil Nadu fishermen.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3  # Local storage
  hive_flutter: ^1.1.0
  location: ^5.0.3  # GPS tracking
  flutter_map: ^6.0.0  # Offline-capable maps
  latlong2: ^0.9.0  # For LatLng handling
  flutter_tts: ^3.8.5  # Voice alerts (supports Tamil)
  vibration: ^1.8.4  # Vibrations
  telephony: ^0.2.0  # SMS sending
  tflite_flutter: ^0.10.4  # On-device AI
  path_provider: ^2.1.1  # File paths for logs/models
  encrypt: ^5.0.3  # Encrypted logs
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png  # Add your logo here
    - assets/models/trajectory_model.tflite  # Your TF Lite model