name: sea_siren_alert
description: App to prevent border crossings for Tamil Nadu fishermen.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Location & Maps
  geolocator: ^12.0.0
  latlong2: ^0.8.2
  flutter_local_notifications: ^17.2.3
  flutter_tts: ^4.0.2
  telephony: ^0.2.0
  encrypt: ^5.0.3
  tflite_flutter: ^0.10.4   # For TensorFlow Lite

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/models/trajectory_model.tflite
