name: sea_siren_alert
description: App to prevent border crossings for Tamil fishermen.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  geolocator: ^10.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^15.0.0
  flutter_tts: ^3.7.0
  telephony: ^0.2.0
  encrypt: ^5.0.1
  path_provider: ^2.0.15
  latlong2: ^0.9.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/offline_tiles/
    - assets/sounds/